#pragma once
static const char index_html[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32 PWM Control</title>"
"<style>"
":root{"
"--bg:#0a0c10;"
"--surface:#12151c;"
"--surface2:#1a1f2b;"
"--border:#252c3a;"
"--accent:#00e5ff;"
"--accent2:#7c3aed;"
"--warn:#f59e0b;"
"--danger:#ef4444;"
"--ok:#10b981;"
"--text:#e2e8f0;"
"--muted:#64748b;"
"--font:'Courier New',monospace;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--text);font-family:var(--font);min-height:100vh;overflow-x:hidden}"
/* scanline overlay */
"body::before{content:'';position:fixed;inset:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,229,255,.015) 2px,rgba(0,229,255,.015) 4px);pointer-events:none;z-index:9999}"
/* ---- PAGE ---- */
".page{display:none;animation:fadeIn .3s ease}"
".page.active{display:block}"
"@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}"
/* ---- HEADER ---- */
"header{padding:18px 24px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:16px;background:var(--surface)}"
".logo{font-size:11px;letter-spacing:.15em;color:var(--accent);text-transform:uppercase}"
".logo span{color:var(--muted)}"
".back-btn{background:none;border:1px solid var(--border);color:var(--muted);padding:4px 12px;border-radius:4px;cursor:pointer;font-family:var(--font);font-size:11px;letter-spacing:.08em;transition:.2s}"
".back-btn:hover{border-color:var(--accent);color:var(--accent)}"
/* ---- MAIN MENU ---- */
".menu-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px;padding:32px 24px;max-width:900px;margin:0 auto}"
".test-card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:28px 24px;cursor:pointer;transition:.25s;position:relative;overflow:hidden}"
".test-card::before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,transparent 60%,rgba(0,229,255,.04));pointer-events:none}"
".test-card:hover{border-color:var(--accent);transform:translateY(-2px);box-shadow:0 8px 32px rgba(0,229,255,.12)}"
".test-card .tc-tag{font-size:10px;letter-spacing:.2em;color:var(--accent);text-transform:uppercase;margin-bottom:10px}"
".test-card h2{font-size:20px;font-weight:700;letter-spacing:.04em;margin-bottom:8px}"
".test-card p{font-size:12px;color:var(--muted);line-height:1.6}"
".test-card .tc-phases{margin-top:16px;display:flex;gap:6px}"
".phase-dot{width:28px;height:28px;border-radius:50%;border:1.5px solid var(--border);display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700}"
".phase-dot.a{border-color:#00e5ff;color:#00e5ff}"
".phase-dot.b{border-color:#7c3aed;color:#7c3aed}"
".phase-dot.c{border-color:#f59e0b;color:#f59e0b}"
/* ---- INNER PAGE ---- */
".inner{max-width:960px;margin:0 auto;padding:24px}"
".page-title{font-size:13px;letter-spacing:.2em;color:var(--accent);text-transform:uppercase;margin-bottom:20px}"
/* ---- GRID LAYOUT ---- */
".two-col{display:grid;grid-template-columns:1fr 1fr;gap:20px}"
"@media(max-width:640px){.two-col{grid-template-columns:1fr}}"
/* ---- CARD ---- */
".card{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:20px}"
".card-title{font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:var(--muted);margin-bottom:16px;padding-bottom:10px;border-bottom:1px solid var(--border)}"
/* ---- MODE TABS ---- */
".mode-tabs{display:flex;gap:4px;margin-bottom:16px;background:var(--bg);border-radius:6px;padding:3px}"
".mode-tab{flex:1;padding:7px;text-align:center;font-size:11px;letter-spacing:.1em;cursor:pointer;border-radius:4px;transition:.2s;border:none;background:none;color:var(--muted);font-family:var(--font)}"
".mode-tab.active{background:var(--accent2);color:#fff}"
/* ---- INPUTS ---- */
".field{margin-bottom:12px}"
".field label{display:block;font-size:10px;letter-spacing:.12em;color:var(--muted);margin-bottom:4px;text-transform:uppercase}"
".field input{width:100%;background:var(--bg);border:1px solid var(--border);border-radius:4px;color:var(--text);font-family:var(--font);font-size:13px;padding:8px 10px;transition:.2s}"
".field input:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 2px rgba(0,229,255,.1)}"
".field input:disabled{opacity:.35}"
/* ---- BUTTONS ---- */
".btn{display:inline-block;padding:9px 18px;border-radius:5px;font-family:var(--font);font-size:11px;letter-spacing:.12em;cursor:pointer;border:1.5px solid;transition:.2s;text-transform:uppercase}"
".btn-primary{background:var(--accent);border-color:var(--accent);color:#000;font-weight:700}"
".btn-primary:hover{background:#00c4db;border-color:#00c4db}"
".btn-danger{background:transparent;border-color:var(--danger);color:var(--danger)}"
".btn-danger:hover{background:var(--danger);color:#fff}"
".btn-ghost{background:transparent;border-color:var(--border);color:var(--muted)}"
".btn-ghost:hover{border-color:var(--accent);color:var(--accent)}"
".btn-row{display:flex;gap:10px;margin-top:16px;flex-wrap:wrap}"
/* ---- PHASE SELECTOR ---- */
".phase-sel{display:flex;gap:8px;margin-bottom:16px}"
".phase-btn{flex:1;padding:8px;text-align:center;border-radius:5px;border:1.5px solid var(--border);cursor:pointer;font-size:12px;font-weight:700;font-family:var(--font);background:none;color:var(--muted);transition:.2s}"
".phase-btn:hover{border-color:var(--accent);color:var(--accent)}"
".phase-btn.sel-A{border-color:#00e5ff;color:#00e5ff;background:rgba(0,229,255,.08)}"
".phase-btn.sel-B{border-color:#7c3aed;color:#7c3aed;background:rgba(124,58,237,.08)}"
".phase-btn.sel-C{border-color:#f59e0b;color:#f59e0b;background:rgba(245,158,11,.08)}"
/* ---- STATUS PANEL ---- */
".status-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:8px;margin-top:12px}"
".stat-item{background:var(--bg);border:1px solid var(--border);border-radius:5px;padding:10px 12px}"
".stat-label{font-size:9px;letter-spacing:.15em;color:var(--muted);text-transform:uppercase;margin-bottom:3px}"
".stat-val{font-size:13px;font-weight:700;color:var(--text)}"
/* running indicator */
".run-badge{display:inline-flex;align-items:center;gap:6px;font-size:11px;letter-spacing:.1em;padding:4px 10px;border-radius:20px;border:1px solid var(--border)}"
".run-badge.running{border-color:var(--ok);color:var(--ok)}"
".run-badge.idle{color:var(--muted)}"
".run-dot{width:7px;height:7px;border-radius:50%;background:var(--muted)}"
".run-badge.running .run-dot{background:var(--ok);animation:pulse 1s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}"
/* seq steps visualization */
".seq-vis{display:flex;gap:6px;margin-top:12px;flex-wrap:wrap}"
".seq-step{padding:4px 10px;border-radius:3px;font-size:10px;letter-spacing:.08em;border:1px solid var(--border);color:var(--muted)}"
".seq-step.done{border-color:var(--ok);color:var(--ok)}"
".seq-step.active-s{border-color:var(--accent);color:var(--accent);background:rgba(0,229,255,.07)}"
/* locked state */
".locked{pointer-events:none;opacity:.45}"
/* section divider */
".divider{border:none;border-top:1px solid var(--border);margin:20px 0}"
"</style>"
"</head>"
"<body>"
/* ============================================================
  PAGE: MAIN MENU
  ============================================================ */
"<div id='pg-menu' class='page active'>"
"<header>"
"<div class='logo'>ESP32 <span>/</span> PWM CONTROLLER</div>"
"</header>"
"<div style='padding:24px 24px 8px;max-width:900px;margin:0 auto'>"
"<p style='font-size:11px;color:var(--muted);letter-spacing:.08em'>SELECT TEST MODE</p>"
"</div>"
"<div class='menu-grid'>"
"<div class='test-card' onclick=\"goPage('pg-single')\">"
"<div class='tc-tag'>Test 01</div>"
"<h2>Single Phase</h2>"
"<p>Apply a fixed PWM duty cycle to one selected phase. Three input methods: CALC formula, Ton, or Duty %.</p>"
"<div class='tc-phases'>"
"<div class='phase-dot a'>A</div>"
"</div>"
"</div>"
"<div class='test-card' onclick=\"goPage('pg-rframe')\">"
"<div class='tc-tag'>Test 02</div>"
"<h2>R Frame</h2>"
"<p>Two-phase sequenced test with inrush (50 ms) + steady state. Phase B starts 1 ms after Phase A reaches steady.</p>"
"<div class='tc-phases'>"
"<div class='phase-dot a'>A</div>"
"<div class='phase-dot b'>B</div>"
"</div>"
"</div>"
"<div class='test-card' onclick=\"goPage('pg-vframe')\">"
"<div class='tc-tag'>Test 03</div>"
"<h2>V Frame</h2>"
"<p>Three-phase sequenced test. Each phase: inrush 50 ms → steady state, offset by 51 ms from the previous.</p>"
"<div class='tc-phases'>"
"<div class='phase-dot a'>A</div>"
"<div class='phase-dot b'>B</div>"
"<div class='phase-dot c'>C</div>"
"</div>"
"</div>"
"</div>"
"</div>"
/* ============================================================
  PAGE: SINGLE PHASE
  ============================================================ */
"<div id='pg-single' class='page'>"
"<header>"
"<button class='back-btn' onclick=\"goPage('pg-menu')\">&#8592; MENU</button>"
"<div class='logo'>SINGLE PHASE TEST</div>"
"</header>"
"<div class='inner'>"
"<div id='single-lock'>"
"<div class='two-col'>"
/* Params card */
"<div class='card'>"
"<div class='card-title'>Parameters</div>"
"<div class='mode-tabs'>"
"<button class='mode-tab active' onclick=\"setSingleMode('calc',this)\">CALC</button>"
"<button class='mode-tab' onclick=\"setSingleMode('ton',this)\">TON</button>"
"<button class='mode-tab' onclick=\"setSingleMode('duty',this)\">DUTY %</button>"
"</div>"
"<div class='field'><label>Frequency (Hz)</label><input id='s-freq' type='number' value='16000'></div>"
"<div id='s-calc-fields'>"
"<div class='field'><label>I (A)</label><input id='s-I' type='number'></div>"
"<div class='field'><label>Rs (Ω)</label><input id='s-Rs' type='number'></div>"
"<div class='field'><label>Vpwm (V)</label><input id='s-Vpwm' type='number'></div>"
"<div class='field'><label>R3 (Ω)</label><input id='s-R3' type='number'></div>"
"<div class='field'><label>R5 (Ω)</label><input id='s-R5' type='number'></div>"
"</div>"
"<div id='s-ton-field' style='display:none'><div class='field'><label>Ton (s)</label><input id='s-Ton' type='number' step='0.000001'></div></div>"
"<div id='s-duty-field' style='display:none'><div class='field'><label>Duty (%)</label><input id='s-Duty' type='number'></div></div>"
"<hr class='divider'>"
"<div class='card-title'>Phase Selection</div>"
"<div class='phase-sel'>"
"<button class='phase-btn sel-A' id='pbA' onclick=\"selPhase('A')\">A</button>"
"<button class='phase-btn' id='pbB' onclick=\"selPhase('B')\">B</button>"
"<button class='phase-btn' id='pbC' onclick=\"selPhase('C')\">C</button>"
"</div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='sendSingleParams()'>SEND PARAMS</button>"
"</div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='startSingle()'>START TEST</button>"
"</div>"
"</div>"
/* Status card */
"<div class='card'>"
"<div class='card-title'>ESP32 Status</div>"
"<div id='s-badge' class='run-badge idle'><div class='run-dot'></div><span>IDLE</span></div>"
"<div class='status-grid' style='margin-top:14px'>"
"<div class='stat-item'><div class='stat-label'>Mode</div><div class='stat-val' id='s-st-mode'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Phase</div><div class='stat-val' id='s-st-phase'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Frequency</div><div class='stat-val' id='s-st-freq'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Gain</div><div class='stat-val' id='s-st-gain'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ts (s)</div><div class='stat-val' id='s-st-ts'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton (s)</div><div class='stat-val' id='s-st-ton'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Toff (s)</div><div class='stat-val' id='s-st-toff'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty %</div><div class='stat-val' id='s-st-duty'>-</div></div>"
"</div>"
"<hr class='divider'>"
"<div class='card-title'>Inputs Received</div>"
"<div class='status-grid'>"
"<div class='stat-item'><div class='stat-label'>I</div><div class='stat-val' id='s-st-I'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Rs</div><div class='stat-val' id='s-st-Rs'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Vpwm</div><div class='stat-val' id='s-st-Vpwm'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>R3</div><div class='stat-val' id='s-st-R3'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>R5</div><div class='stat-val' id='s-st-R5'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton direct</div><div class='stat-val' id='s-st-ton-d'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty direct</div><div class='stat-val' id='s-st-duty-d'>-</div></div>"
"</div>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class='btn-row' style='margin-top:16px'>"
"<button class='btn btn-danger' onclick='stopTest()'>STOP</button>"
"</div>"
"</div>"
/* ============================================================
  PAGE: R FRAME
  ============================================================ */
"<div id='pg-rframe' class='page'>"
"<header>"
"<button class='back-btn' onclick=\"goPage('pg-menu')\">&#8592; MENU</button>"
"<div class='logo'>R FRAME TEST <span style='color:var(--muted)'>&mdash; PHASE A + B</span></div>"
"</header>"
"<div class='inner'>"
"<div id='rf-lock'>"
"<div class='two-col'>"
/* Params card */
"<div>"
"<div class='card' style='margin-bottom:16px'>"
"<div class='card-title' style='color:#00e5ff'>Inrush Parameters <span style='color:var(--muted)'>(first 50 ms, all phases)</span></div>"
"<div class='mode-tabs'>"
"<button class='mode-tab active' onclick=\"setFrameMode('inrush','calc',this)\">CALC</button>"
"<button class='mode-tab' onclick=\"setFrameMode('inrush','ton',this)\">TON</button>"
"<button class='mode-tab' onclick=\"setFrameMode('inrush','duty',this)\">DUTY %</button>"
"</div>"
"<div class='field'><label>Frequency (Hz)</label><input id='rf-in-freq' type='number' value='16000'></div>"
"<div id='rf-in-calc'>"
"<div class='field'><label>I (A)</label><input id='rf-in-I' type='number'></div>"
"<div class='field'><label>Rs (Ω)</label><input id='rf-in-Rs' type='number'></div>"
"<div class='field'><label>Vpwm (V)</label><input id='rf-in-Vpwm' type='number'></div>"
"<div class='field'><label>R3 (Ω)</label><input id='rf-in-R3' type='number'></div>"
"<div class='field'><label>R5 (Ω)</label><input id='rf-in-R5' type='number'></div>"
"</div>"
"<div id='rf-in-ton' style='display:none'><div class='field'><label>Ton (s)</label><input id='rf-in-Ton' type='number' step='0.000001'></div></div>"
"<div id='rf-in-duty' style='display:none'><div class='field'><label>Duty (%)</label><input id='rf-in-Duty' type='number'></div></div>"
"</div>"
"<div class='card'>"
"<div class='card-title' style='color:#7c3aed'>Steady State Parameters <span style='color:var(--muted)'>(after 50 ms, stays)</span></div>"
"<div class='mode-tabs'>"
"<button class='mode-tab active' onclick=\"setFrameMode('steady','calc',this)\">CALC</button>"
"<button class='mode-tab' onclick=\"setFrameMode('steady','ton',this)\">TON</button>"
"<button class='mode-tab' onclick=\"setFrameMode('steady','duty',this)\">DUTY %</button>"
"</div>"
"<div class='field'><label>Frequency (Hz)</label><input id='rf-st-freq' type='number' value='16000'></div>"
"<div id='rf-st-calc'>"
"<div class='field'><label>I (A)</label><input id='rf-st-I' type='number'></div>"
"<div class='field'><label>Rs (Ω)</label><input id='rf-st-Rs' type='number'></div>"
"<div class='field'><label>Vpwm (V)</label><input id='rf-st-Vpwm' type='number'></div>"
"<div class='field'><label>R3 (Ω)</label><input id='rf-st-R3' type='number'></div>"
"<div class='field'><label>R5 (Ω)</label><input id='rf-st-R5' type='number'></div>"
"</div>"
"<div id='rf-st-ton' style='display:none'><div class='field'><label>Ton (s)</label><input id='rf-st-Ton' type='number' step='0.000001'></div></div>"
"<div id='rf-st-duty' style='display:none'><div class='field'><label>Duty (%)</label><input id='rf-st-Duty' type='number'></div></div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='sendFrameParams(\"rf\")'> SEND PARAMS</button>"
"</div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='startRFrame()'>START R FRAME</button>"
"</div>"
"</div>"
"</div>"
/* Status card */
"<div class='card'>"
"<div class='card-title'>ESP32 Status</div>"
"<div id='rf-badge' class='run-badge idle'><div class='run-dot'></div><span>IDLE</span></div>"
"<div style='margin-top:14px'>"
"<div class='card-title'>Sequence</div>"
"<div class='seq-vis' id='rf-seq'>"
"<div class='seq-step' id='rf-sq0'>A Inrush</div>"
"<div class='seq-step' id='rf-sq1'>A Steady</div>"
"<div class='seq-step' id='rf-sq2'>B Inrush</div>"
"<div class='seq-step' id='rf-sq3'>B Steady</div>"
"</div>"
"</div>"
"<hr class='divider'>"
"<div class='card-title'>Inrush (from ESP)</div>"
"<div class='status-grid'>"
"<div class='stat-item'><div class='stat-label'>Mode</div><div class='stat-val' id='rf-in-st-mode'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Freq</div><div class='stat-val' id='rf-in-st-freq'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton</div><div class='stat-val' id='rf-in-st-ton'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty %</div><div class='stat-val' id='rf-in-st-duty'>-</div></div>"
"</div>"
"<hr class='divider'>"
"<div class='card-title'>Steady State (from ESP)</div>"
"<div class='status-grid'>"
"<div class='stat-item'><div class='stat-label'>Mode</div><div class='stat-val' id='rf-st-st-mode'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Freq</div><div class='stat-val' id='rf-st-st-freq'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton</div><div class='stat-val' id='rf-st-st-ton'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty %</div><div class='stat-val' id='rf-st-st-duty'>-</div></div>"
"</div>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class='btn-row' style='margin-top:16px'>"
"<button class='btn btn-danger' onclick='stopTest()'>STOP</button>"
"</div>"
"</div>"
/* ============================================================
  PAGE: V FRAME
  ============================================================ */
"<div id='pg-vframe' class='page'>"
"<header>"
"<button class='back-btn' onclick=\"goPage('pg-menu')\">&#8592; MENU</button>"
"<div class='logo'>V FRAME TEST <span style='color:var(--muted)'>&mdash; PHASE A + B + C</span></div>"
"</header>"
"<div class='inner'>"
"<div id='vf-lock'>"
"<div class='two-col'>"
/* Params card */
"<div>"
"<div class='card' style='margin-bottom:16px'>"
"<div class='card-title' style='color:#00e5ff'>Inrush Parameters <span style='color:var(--muted)'>(50 ms per phase)</span></div>"
"<div class='mode-tabs'>"
"<button class='mode-tab active' onclick=\"setFrameMode('vinrush','calc',this)\">CALC</button>"
"<button class='mode-tab' onclick=\"setFrameMode('vinrush','ton',this)\">TON</button>"
"<button class='mode-tab' onclick=\"setFrameMode('vinrush','duty',this)\">DUTY %</button>"
"</div>"
"<div class='field'><label>Frequency (Hz)</label><input id='vf-in-freq' type='number' value='16000'></div>"
"<div id='vf-in-calc'>"
"<div class='field'><label>I (A)</label><input id='vf-in-I' type='number'></div>"
"<div class='field'><label>Rs (Ω)</label><input id='vf-in-Rs' type='number'></div>"
"<div class='field'><label>Vpwm (V)</label><input id='vf-in-Vpwm' type='number'></div>"
"<div class='field'><label>R3 (Ω)</label><input id='vf-in-R3' type='number'></div>"
"<div class='field'><label>R5 (Ω)</label><input id='vf-in-R5' type='number'></div>"
"</div>"
"<div id='vf-in-ton' style='display:none'><div class='field'><label>Ton (s)</label><input id='vf-in-Ton' type='number' step='0.000001'></div></div>"
"<div id='vf-in-duty' style='display:none'><div class='field'><label>Duty (%)</label><input id='vf-in-Duty' type='number'></div></div>"
"</div>"
"<div class='card'>"
"<div class='card-title' style='color:#7c3aed'>Steady State Parameters</div>"
"<div class='mode-tabs'>"
"<button class='mode-tab active' onclick=\"setFrameMode('vsteady','calc',this)\">CALC</button>"
"<button class='mode-tab' onclick=\"setFrameMode('vsteady','ton',this)\">TON</button>"
"<button class='mode-tab' onclick=\"setFrameMode('vsteady','duty',this)\">DUTY %</button>"
"</div>"
"<div class='field'><label>Frequency (Hz)</label><input id='vf-st-freq' type='number' value='16000'></div>"
"<div id='vf-st-calc'>"
"<div class='field'><label>I (A)</label><input id='vf-st-I' type='number'></div>"
"<div class='field'><label>Rs (Ω)</label><input id='vf-st-Rs' type='number'></div>"
"<div class='field'><label>Vpwm (V)</label><input id='vf-st-Vpwm' type='number'></div>"
"<div class='field'><label>R3 (Ω)</label><input id='vf-st-R3' type='number'></div>"
"<div class='field'><label>R5 (Ω)</label><input id='vf-st-R5' type='number'></div>"
"</div>"
"<div id='vf-st-ton' style='display:none'><div class='field'><label>Ton (s)</label><input id='vf-st-Ton' type='number' step='0.000001'></div></div>"
"<div id='vf-st-duty' style='display:none'><div class='field'><label>Duty (%)</label><input id='vf-st-Duty' type='number'></div></div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='sendFrameParams(\"vf\")'>SEND PARAMS</button>"
"</div>"
"<div class='btn-row'>"
"<button class='btn btn-primary' onclick='startVFrame()'>START V FRAME</button>"
"</div>"
"</div>"
"</div>"
/* Status card */
"<div class='card'>"
"<div class='card-title'>ESP32 Status</div>"
"<div id='vf-badge' class='run-badge idle'><div class='run-dot'></div><span>IDLE</span></div>"
"<div style='margin-top:14px'>"
"<div class='card-title'>Sequence Timeline</div>"
"<div class='seq-vis' id='vf-seq'>"
"<div class='seq-step' id='vf-sq0'>A Inrush<br><span style='font-size:9px;color:var(--muted)'>0 ms</span></div>"
"<div class='seq-step' id='vf-sq1'>A Steady<br><span style='font-size:9px;color:var(--muted)'>50 ms</span></div>"
"<div class='seq-step' id='vf-sq2'>B Inrush<br><span style='font-size:9px;color:var(--muted)'>51 ms</span></div>"
"<div class='seq-step' id='vf-sq3'>B Steady<br><span style='font-size:9px;color:var(--muted)'>101 ms</span></div>"
"<div class='seq-step' id='vf-sq4'>C Inrush<br><span style='font-size:9px;color:var(--muted)'>102 ms</span></div>"
"<div class='seq-step' id='vf-sq5'>C Steady<br><span style='font-size:9px;color:var(--muted)'>152 ms</span></div>"
"</div>"
"</div>"
"<hr class='divider'>"
"<div class='card-title'>Inrush (from ESP)</div>"
"<div class='status-grid'>"
"<div class='stat-item'><div class='stat-label'>Mode</div><div class='stat-val' id='vf-in-st-mode'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Freq</div><div class='stat-val' id='vf-in-st-freq'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton</div><div class='stat-val' id='vf-in-st-ton'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty %</div><div class='stat-val' id='vf-in-st-duty'>-</div></div>"
"</div>"
"<hr class='divider'>"
"<div class='card-title'>Steady State (from ESP)</div>"
"<div class='status-grid'>"
"<div class='stat-item'><div class='stat-label'>Mode</div><div class='stat-val' id='vf-st-st-mode'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Freq</div><div class='stat-val' id='vf-st-st-freq'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Ton</div><div class='stat-val' id='vf-st-st-ton'>-</div></div>"
"<div class='stat-item'><div class='stat-label'>Duty %</div><div class='stat-val' id='vf-st-st-duty'>-</div></div>"
"</div>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class='btn-row' style='margin-top:16px'>"
"<button class='btn btn-danger' onclick='stopTest()'>STOP</button>"
"</div>"
"</div>"
/* ============================================================
  JAVASCRIPT
  ============================================================ */
"<script>"
/* ---- Navigation ---- */
"function goPage(id){"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.getElementById(id).classList.add('active');"
"}"
/* ---- Single mode tabs ---- */
"var singleMode='calc';"
"function setSingleMode(m,btn){"
"singleMode=m;"
"document.querySelectorAll('#pg-single .mode-tab').forEach(b=>b.classList.remove('active'));"
"btn.classList.add('active');"
"document.getElementById('s-calc-fields').style.display=m==='calc'?'':'none';"
"document.getElementById('s-ton-field').style.display=m==='ton'?'':'none';"
"document.getElementById('s-duty-field').style.display=m==='duty'?'':'none';"
"}"
/* ---- Frame mode tabs ---- */
"var frameModes={inrush:'calc',steady:'calc',vinrush:'calc',vsteady:'calc'};"
"function setFrameMode(group,m,btn){"
"frameModes[group]=m;"
"var pg=group.startsWith('v')?'vf':'rf';"
"var sub=group.startsWith('v')?(group==='vinrush'?'in':'st'):(group==='inrush'?'in':'st');"
"var pfx=pg+'-'+sub;"
"btn.closest('.mode-tabs').querySelectorAll('.mode-tab').forEach(b=>b.classList.remove('active'));"
"btn.classList.add('active');"
"document.getElementById(pfx+'-calc').style.display=m==='calc'?'':'none';"
"document.getElementById(pfx+'-ton').style.display=m==='ton'?'':'none';"
"document.getElementById(pfx+'-duty').style.display=m==='duty'?'':'none';"
"}"
/* ---- Phase selector (single) ---- */
"var selPh='A';"
"function selPhase(p){"
"selPh=p;"
"['A','B','C'].forEach(x=>{"
"var b=document.getElementById('pb'+x);"
"b.className='phase-btn'+(p===x?' sel-'+x:'');"
"});"
"fetch('/phase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phase:p})});"
"}"
/* ---- Build param payload from a prefix ---- */
"function buildPayload(pfx,modeKey){"
"var m=frameModes[modeKey]||'calc';"
"var freq=parseFloat(document.getElementById(pfx+'-freq').value)||0;"
"var obj={mode:m,Frequency:freq};"
"if(m==='calc'){"
"obj.I    =parseFloat(document.getElementById(pfx+'-I').value)||0;"
"obj.Rs   =parseFloat(document.getElementById(pfx+'-Rs').value)||0;"
"obj.Vpwm =parseFloat(document.getElementById(pfx+'-Vpwm').value)||0;"
"obj.R3   =parseFloat(document.getElementById(pfx+'-R3').value)||0;"
"obj.R5   =parseFloat(document.getElementById(pfx+'-R5').value)||0;"
"}else if(m==='ton'){"
"obj.direct_mode='ton';"
"obj.Ton=parseFloat(document.getElementById(pfx+'-Ton').value)||0;"
"}else{"
"obj.direct_mode='duty';"
"obj.Duty=parseFloat(document.getElementById(pfx+'-Duty').value)||0;"
"}"
"return obj;"
"}"
/* ---- Send single params ---- */
"function sendSingleParams(){"
"var m=singleMode;"
"var payload={mode:m,Frequency:parseFloat(document.getElementById('s-freq').value)||0};"
"if(m==='calc'){"
"payload.I    =parseFloat(document.getElementById('s-I').value)||0;"
"payload.Rs   =parseFloat(document.getElementById('s-Rs').value)||0;"
"payload.Vpwm =parseFloat(document.getElementById('s-Vpwm').value)||0;"
"payload.R3   =parseFloat(document.getElementById('s-R3').value)||0;"
"payload.R5   =parseFloat(document.getElementById('s-R5').value)||0;"
"}else if(m==='ton'){"
"payload.direct_mode='ton';"
"payload.Ton=parseFloat(document.getElementById('s-Ton').value)||0;"
"}else{"
"payload.direct_mode='duty';"
"payload.Duty=parseFloat(document.getElementById('s-Duty').value)||0;"
"}"
"fetch('/params/single',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});"
"}"
/* ---- Send frame params ---- */
"function sendFrameParams(pg){"
"var inPfx,stPfx,inKey,stKey;"
"if(pg==='rf'){inPfx='rf-in';stPfx='rf-st';inKey='inrush';stKey='steady';}"
"else{inPfx='vf-in';stPfx='vf-st';inKey='vinrush';stKey='vsteady';}"
"var payload={inrush:buildPayload(inPfx,inKey),steady:buildPayload(stPfx,stKey)};"
"fetch('/params/frame',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});"
"}"
/* ---- Start tests ---- */
"function startSingle(){fetch('/test/single/start',{method:'POST'});}"
"function startRFrame(){fetch('/test/rframe/start',{method:'POST'});}"
"function startVFrame(){fetch('/test/vframe/start',{method:'POST'});}"
"function stopTest(){fetch('/test/stop',{method:'POST'});}"
/* ---- Helper: set text ---- */
"function setText(id,v){var e=document.getElementById(id);if(e)e.innerText=v;}"
"function setNum(id,v,dec){setText(id,isNaN(v)?'-':Number(v).toFixed(dec));}"
/* ---- Update sequence visualization ---- */
"function updateSeqVis(prefix,steps,step,running){"
"for(var i=0;i<steps;i++){"
"var el=document.getElementById(prefix+i);"
"if(!el)continue;"
"el.className='seq-step';"
"if(!running)continue;"
"if(i<step)el.classList.add('done');"
"else if(i===step)el.classList.add('active-s');"
"}"
"}"
/* ---- Update badge ---- */
"function updateBadge(id,running){"
"var b=document.getElementById(id);"
"if(!b)return;"
"b.className='run-badge '+(running?'running':'idle');"
"b.querySelector('span').innerText=running?'RUNNING':'IDLE';"
"}"
/* ---- Lock controls while running ---- */
"function setLock(id,locked){"
"var e=document.getElementById(id);"
"if(e)e.className=locked?'locked':'';"
"}"
/* ---- Poll state ---- */
"function pollState(){"
"fetch('/state').then(function(r){return r.json();}).then(function(s){"
"var running=s.running;"
"var test=s.active_test;"
"var step=s.seq_step||0;"
/* Single page */
"if(document.getElementById('pg-single').classList.contains('active')){"
"updateBadge('s-badge',running&&test==='SINGLE');"
"setLock('single-lock',running&&test==='SINGLE');"
"var sp=s.single||{};"
"setText('s-st-mode',sp.mode||'-');"
"setText('s-st-phase',s.phase||'-');"
"setNum('s-st-freq',sp.Frequency,2);"
"setNum('s-st-gain',sp.Gain,4);"
"setNum('s-st-ts',sp.Ts,6);"
"setNum('s-st-ton',sp.Ton,6);"
"setNum('s-st-toff',sp.Toff,6);"
"setNum('s-st-duty',sp.Duty_used,2);"
"setNum('s-st-I',sp.I,3);"
"setNum('s-st-Rs',sp.Rs,3);"
"setNum('s-st-Vpwm',sp.Vpwm,3);"
"setNum('s-st-R3',sp.R3,2);"
"setNum('s-st-R5',sp.R5,2);"
"setNum('s-st-ton-d',sp.Ton_direct,6);"
"setNum('s-st-duty-d',sp.Duty_direct,2);"
"}"
/* R Frame page */
"if(document.getElementById('pg-rframe').classList.contains('active')){"
"var rfRun=running&&test==='R_FRAME';"
"updateBadge('rf-badge',rfRun);"
"setLock('rf-lock',rfRun);"
"updateSeqVis('rf-sq',4,step,rfRun);"
"var ip=s.inrush||{},sp2=s.steady||{};"
"setText('rf-in-st-mode',ip.mode||'-');"
"setNum('rf-in-st-freq',ip.Frequency,2);"
"setNum('rf-in-st-ton',ip.Ton,6);"
"setNum('rf-in-st-duty',ip.Duty_used,2);"
"setText('rf-st-st-mode',sp2.mode||'-');"
"setNum('rf-st-st-freq',sp2.Frequency,2);"
"setNum('rf-st-st-ton',sp2.Ton,6);"
"setNum('rf-st-st-duty',sp2.Duty_used,2);"
"}"
/* V Frame page */
"if(document.getElementById('pg-vframe').classList.contains('active')){"
"var vfRun=running&&test==='V_FRAME';"
"updateBadge('vf-badge',vfRun);"
"setLock('vf-lock',vfRun);"
"updateSeqVis('vf-sq',6,step,vfRun);"
"var ip2=s.inrush||{},sp3=s.steady||{};"
"setText('vf-in-st-mode',ip2.mode||'-');"
"setNum('vf-in-st-freq',ip2.Frequency,2);"
"setNum('vf-in-st-ton',ip2.Ton,6);"
"setNum('vf-in-st-duty',ip2.Duty_used,2);"
"setText('vf-st-st-mode',sp3.mode||'-');"
"setNum('vf-st-st-freq',sp3.Frequency,2);"
"setNum('vf-st-st-ton',sp3.Ton,6);"
"setNum('vf-st-st-duty',sp3.Duty_used,2);"
"}"
"}).catch(function(){});"
"}"
"setInterval(pollState,500);"
"</script>"
"</body>"
"</html>";